name: Validate Contracts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate contracts
        run: |
          find . -name "contrato_proceso.yml" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Validating $file"
            ajv validate -s .schemas/contrato_proceso.schema.json -d "$file" --valid
            if [ $? -ne 0 ]; then
              echo "Validation failed for $file"
              exit 1
            fi
          done
          echo "All contracts are valid."
